fixup

diff --git a/.github/workflows/publish_next.yml b/.github/workflows/publish_next.yml
--- a/.github/workflows/publish_next.yml
+++ b/.github/workflows/publish_next.yml
@@ -40,7 +40,8 @@ jobs:
         shell: bash
         run: |
           if [[ ! "$(npm pkg get version)" =~ ^\"[0-9]+\.[0-9]+\.[0-9]\-next\.[0-9]+\"$ ]]; then
-            echo "::error::Invalid version name.\nCannot publish an off-cycle version named: $(npm pkg get version).\nPlease run 'make bump-next-version' to generate a valid version name."
+            echo "::error::Cannot publish an off-cycle version named: $(npm pkg get version). Please run 'make bump-next-version' to generate a valid version name."
+            exit 1
           fi
 
       # - name: Publish
